### ISSUE TITLE
Could not find /src/cog.yaml

### ISSUE THREAD

**Issue by AlexanderKozhevin** [lucataco/cog-civitai-sdxl-template#2]
I tried to start the container
```
ubuntu@pod2:~/cog-civitai-sdxl-template$ sudo docker logs crazy_ganguly
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/predictor.py", line 135, in load_config
    with open(config_path) as fh:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/src/cog.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/server/http.py", line 351, in <module>
    config = load_config()
             ^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/predictor.py", line 138, in load_config
    raise ConfigDoesNotExist(
cog.errors.ConfigDoesNotExist: Could not find /src/cog.yaml
```

But it's working fine, when I use cog predict -i prompt="An astronaut riding a rainbow unicorn"

**Comment by AlexanderKozhevin** [comment]
forgot cog build
